{% set name = "urbansim_defaults" %}
{% set version = "0.1.1" %}
{% set sha256 = "45d33f73e1c6d60744b07ac4d81fee1e8270caed3b8c4451ae07b89eb6d3dc26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - urbansim_defaults

about:
  home: https://github.com/udst/urbansim_defaults
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Starter models and functionality to use with UrbanSim'
  doc_url: https://udst.github.io/urbansim_defaults/
  dev_url: https://github.com/udst/urbansim_defaults

extra:
  recipe-maintainers:
    - smmaurer
