travis:
  secure:
    BINSTAR_TOKEN: QcJamfKojbwG/oYJhWQJ6tO2Wm8tkt+fKhIFEk55aZ3Vzut0OHIYgC67BeECGaKENsT3y2PHma6aBqP21JVJ8zEghMwOyPYed8Qtb77JQn2xcSDTXlpo/bsV+GF8cCshcXsqxHcTKCxLeywpx46neimvgzAGe3wqWOHi7RVsK4QouPjsmvw+589FVrPd77kY5yBYgLc0tDzs+x+YkGu3IFuXch0qcbaYWcx6x7P0kwYYV/Z8NLtSkO445x8FM92wFJp4diknN9DC6YUtI/QSyr+zWMFmpV0UwBl/wOELvKfWXVqmnY98/TVXSTouxdcDzW34T5yBRT3CRGqvJKKAILXpb1+EXNtUdaBLyErDpSp48suKBZAv85MHU15xRcLTWG3azjZeeJdxtTE00Om7dYHSeeX8GXFOdmRvX1xT0BjFoDW0CJRXlP+6H+o8/lGhbTgK0NX6Rz0OQiLdSBAHf8EsUZ3dA5pbyfSXlm9EJkG4kL+OzEkCWkcN1eqrOBMFWNaBaHGTDs5ZwfF3jjXnnlJ4RdnRqghYYdMC7SR13xCG4lN4/kIhFf9+JaJ575GoN2j316lt5AHB4n6ZnusjVsRbBxxoHwAcL0z/mS3miAgowfFOCCzsyU4znpxfJGmNapfEXhNxyQirKeBfLaPc41sfKaa0ccSXa+1X4pJKJEc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
